actions:
- name: start_gm
  gpu_id: all
  plugin: gm
  core_clock: true
  mem_clock: true
  temperature: true
  power: true
  max_pcie_replays: 1
  monitor: true
  monitor_interval: 1000
- name: test_pciebw
  gpu_id: all
  plugin: pciebw
  device_to_host: true
  host_to_device: true
  pinned: true
  duration: 5
- name: start_gm
  gpu_id: all
  plugin: gm
  monitor: false
  monitor_interval: 1000
