actions:
- name: jpeg_decode_single_channel_test
  plugin: video
  channel_num: 1
  times: 100
  compare: 1
  channel_paths: "/tmp/video_samples/dec_jpeg/vectors/ch_00007fff78022590/"
- name: jpeg_decode_multi_channels_test
  plugin: video
  channel_num: 16
  times: 100
  compare: 1
  channel_paths_root: "/tmp/video_samples/dec_jpeg/vectors/"
