#!/usr/bin/env bash
# Apply a vLLM/SGLang Kubernetes YAML (generated by utils/k8s_yaml_gen.sh) and
# start the service. Framework-agnostic: the framework, config path, and server
# script are read from the YAML's infer.birentech.com/* annotations.
#
# Usage:
#   bash utils/k8s_apply.sh <yaml_file> [log_dir]
#
#   yaml_file  YAML generated by k8s_yaml_gen.sh (--task deploy or --task pod)
#   log_dir    (pod type only) Directory inside the pod where the server run script
#              is written and the interactive shell starts. Default: /tmp
#
# Behaviour by workload type:
#   Deployment  Apply YAML, wait for readiness probe, run an API smoke test.
#   Pod         Apply YAML, wait for Running, write a ready-to-run server script
#               (<log_dir>/run_<framework>_<model>_server.sh) inside the pod, then
#               enter an interactive shell. The user then starts the server manually.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # .../infer/llm/utils
LLM_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

_info() { echo -e "\033[0;36m[INFO]\033[0m  $*"; }
_ok()   { echo -e "\033[1;32m[ OK ]\033[0m  $*"; }
_warn() { echo -e "\033[0;33m[WARN]\033[0m  $*"; }
_err()  { echo -e "\033[0;31m[ERR ]\033[0m  $*" >&2; }

usage() {
    echo ""
    echo "Usage: $0 <yaml_file> [log_dir]"
    echo ""
    echo "  yaml_file   YAML generated by k8s_yaml_gen.sh (--task deploy or --task pod)"
    echo "  log_dir     (pod type only) directory inside pod for server run script [default: /tmp]"
    echo ""
    exit 1
}

[[ $# -lt 1 ]] && { _err "A YAML file is required."; usage; }

YAML_FILE="$1"
LOG_DIR="${2:-/tmp}"

[[ "$YAML_FILE" != /* ]] && YAML_FILE="$(pwd)/${YAML_FILE}"
[[ ! -f "$YAML_FILE" ]] && { _err "YAML file not found: $YAML_FILE"; exit 1; }

# ── Detect workload type ───────────────────────────────────────────────────────
K8S_KIND=$(awk '/^kind: Deployment/{print "deploy"; exit} /^kind: Pod/{print "pod"; exit}' "$YAML_FILE")
[[ -z "$K8S_KIND" ]] && { _err "Cannot determine workload type (Deployment or Pod) from: $YAML_FILE"; exit 1; }

# ── Parse common metadata (unified infer.birentech.com/* annotations) ──────────
NAMESPACE=$(awk '/^kind: Namespace/{f=1} f && /^  name:/{print $2; exit}' "$YAML_FILE")
NODE_NAME=$(awk '/nodeName:/{print $2; exit}' "$YAML_FILE")
CONFIG_FILE=$(awk '/infer\.birentech\.com\/config-file:/{gsub(/"/, "", $2); print $2; exit}' "$YAML_FILE")
INNER_SCRIPT=$(awk '/infer\.birentech\.com\/server-script:/{gsub(/"/, "", $2); print $2; exit}' "$YAML_FILE")

for var in NAMESPACE CONFIG_FILE INNER_SCRIPT; do
    [[ -z "${!var}" ]] && { _err "Failed to parse ${var} from YAML: ${YAML_FILE}"; exit 1; }
done
[[ ! -f "$CONFIG_FILE" ]] && { _err "Config file not found: $CONFIG_FILE"; exit 1; }

# ── Parse config (framework + serving params) ──────────────────────────────────
# shellcheck source=./parse_config.sh
source "${SCRIPT_DIR}/parse_config.sh"
parse_config "$CONFIG_FILE" || exit 1
task="${task:-}"   # vllm-only field; absent for sglang

# ── Registry lookup (for the model API name in smoke tests) ────────────────────
# shellcheck source=../model_registry.sh
source "${LLM_DIR}/model_registry.sh"
parse_model "$model_weights" || exit 1
MODEL_API="${served_model_name:-${MODEL_PATH}}"

# ── Resolve node IP (NODE_NAME may be empty under default label scheduling) ────
NODE_IP=""
if [[ -n "${NODE_NAME:-}" ]]; then
    NODE_IP=$(kubectl get node "$NODE_NAME" \
        -o jsonpath='{range .status.addresses[*]}{.type}{"\t"}{.address}{"\n"}{end}' \
        2>/dev/null | awk '$1=="InternalIP"{print $2; exit}' || true)
    [[ -z "$NODE_IP" ]] && NODE_IP="$NODE_NAME"
fi

_info "YAML        : $YAML_FILE  [framework=${framework} type=${K8S_KIND}]"
_info "Namespace   : $NAMESPACE"
[[ -n "${NODE_NAME:-}" ]] && _info "Node        : $NODE_NAME  ($NODE_IP)"
_info "Config      : $CONFIG_FILE"
echo ""

# ══════════════════════════════════════════════════════════════════════════════
# DEPLOY path — apply, wait for readiness, smoke test
# ══════════════════════════════════════════════════════════════════════════════
if [[ "$K8S_KIND" == "deploy" ]]; then

    DEPLOY_NAME=$(awk '/^kind: Deployment/{f=1} f && /^  name:/{print $2; exit}' "$YAML_FILE")
    SVC_NAME=$(awk '/^kind: Service/{f=1} f && /^  name:/{print $2; exit}' "$YAML_FILE")
    APP_LABEL=$(awk '/matchLabels:/{f=1} f && /app:/{print $2; exit}' "$YAML_FILE")
    NODEPORT=$(awk '/nodePort:/{print $2; exit}' "$YAML_FILE")
    INITIAL_DELAY=$(awk '/initialDelaySeconds:/{print $2; exit}' "$YAML_FILE")

    for var in DEPLOY_NAME SVC_NAME APP_LABEL NODEPORT INITIAL_DELAY; do
        [[ -z "${!var}" ]] && { _err "Failed to parse ${var} from YAML: ${YAML_FILE}"; exit 1; }
    done

    _info "Deployment  : $DEPLOY_NAME  →  Service: $SVC_NAME"
    _info "NodePort    : $NODEPORT"
    echo ""

    kubectl apply -f "$YAML_FILE"
    _ok "Resources applied."
    echo ""

    TIMEOUT=$(( INITIAL_DELAY + 300 ))
    _info "Waiting for Pod to become Ready (~$((INITIAL_DELAY / 60)) min estimated)..."
    _info "Monitor: kubectl logs -n ${NAMESPACE} -l app=${APP_LABEL} -f"
    echo ""

    ELAPSED=0; INTERVAL=15; READY=false
    while [[ $ELAPSED -lt $TIMEOUT ]]; do
        STATUS=$(kubectl get pods -n "$NAMESPACE" -l "app=${APP_LABEL}" \
            --no-headers -o custom-columns='R:.status.containerStatuses[0].ready' \
            2>/dev/null | head -1 || echo "unknown")
        [[ "$STATUS" == "true" ]] && { READY=true; break; }
        printf "."
        sleep $INTERVAL
        ELAPSED=$((ELAPSED + INTERVAL))
    done
    echo ""

    # Determine a node IP to curl the NodePort against.
    if [[ -z "${NODE_IP:-}" ]]; then
        NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}' 2>/dev/null || echo "127.0.0.1")
    fi

    if $READY; then
        _ok "══════════════════════════════════════════════════════"
        _ok " ${framework} server ready — ${DEPLOY_NAME}  NodePort :${NODEPORT}"
        _ok "══════════════════════════════════════════════════════"
        echo ""
        _info "Running API smoke test..."
        echo ""

        if [[ "$task" == "embed" ]]; then
            RESULT=$(curl -sf --noproxy "*" \
                "http://${NODE_IP}:${NODEPORT}/v1/embeddings" \
                -H 'Content-Type: application/json' \
                -d "{\"model\": \"${MODEL_API}\", \"input\": \"Hello, world!\"}" \
                2>/dev/null || true)
            if [[ -n "$RESULT" ]] && echo "$RESULT" | python3 -c "import sys,json; d=json.load(sys.stdin); assert d.get('object')=='list'" 2>/dev/null; then
                _ok "Embedding API smoke test passed"
                echo "$RESULT" | python3 -m json.tool 2>/dev/null | head -12 || true
            else
                _warn "API test returned unexpected response:"; echo "${RESULT:-<empty>}"
            fi
        else
            RESULT=$(curl -sf --noproxy "*" \
                "http://${NODE_IP}:${NODEPORT}/v1/chat/completions" \
                -H 'Content-Type: application/json' \
                -d "{\"model\": \"${MODEL_API}\", \"messages\": [{\"role\": \"user\", \"content\": \"Hello!\"}], \"max_tokens\": 16}" \
                2>/dev/null || true)
            if [[ -n "$RESULT" ]] && echo "$RESULT" | python3 -c "import sys,json; d=json.load(sys.stdin); assert 'choices' in d" 2>/dev/null; then
                _ok "Chat completion API smoke test passed"
                echo "$RESULT" | python3 -m json.tool 2>/dev/null | head -16 || true
            else
                _warn "API test returned unexpected response:"; echo "${RESULT:-<empty>}"
            fi
        fi
    else
        _warn "Pod not Ready after ${TIMEOUT}s — may still be loading or failed."
        _warn "Check: kubectl logs -n ${NAMESPACE} -l app=${APP_LABEL} -f"
    fi

    echo ""
    if [[ "$task" == "embed" ]]; then
        echo "── Embedding test ──────────────────────────────────────────"
        echo "curl -s --noproxy \"*\" http://${NODE_IP}:${NODEPORT}/v1/embeddings \\"
        echo "  -H 'Content-Type: application/json' \\"
        echo "  -d '{\"model\": \"${MODEL_API}\", \"input\": \"Hello, world!\"}' | python3 -m json.tool"
    else
        echo "── Chat completion test ────────────────────────────────────"
        echo "curl -s --noproxy \"*\" http://${NODE_IP}:${NODEPORT}/v1/chat/completions \\"
        echo "  -H 'Content-Type: application/json' \\"
        echo "  -d '{\"model\": \"${MODEL_API}\", \"messages\": [{\"role\": \"user\", \"content\": \"Hello!\"}], \"max_tokens\": 64}' | python3 -m json.tool"
    fi
    echo ""
    echo "── K8s management ──────────────────────────────────────────"
    echo "  kubectl get pods -n ${NAMESPACE}"
    echo "  kubectl logs -n ${NAMESPACE} -l app=${APP_LABEL} -f"
    echo "  kubectl delete deployment/${DEPLOY_NAME} service/${SVC_NAME} -n ${NAMESPACE}"

# ══════════════════════════════════════════════════════════════════════════════
# POD path — apply, wait for Running, write run script, enter interactive shell
# ══════════════════════════════════════════════════════════════════════════════
else

    POD_NAME=$(awk '/^kind: Pod/{f=1} f && /^  name:/{print $2; exit}' "$YAML_FILE")
    [[ -z "$POD_NAME" ]] && { _err "Failed to parse POD_NAME from YAML: ${YAML_FILE}"; exit 1; }

    _info "Pod         : $POD_NAME"
    _info "Log dir     : $LOG_DIR"
    echo ""

    kubectl apply -f "$YAML_FILE"
    _ok "Pod applied."
    echo ""

    _info "Waiting for Pod to reach Running state..."
    ELAPSED=0; TIMEOUT=180; INTERVAL=5; RUNNING=false
    while [[ $ELAPSED -lt $TIMEOUT ]]; do
        PHASE=$(kubectl get pod "$POD_NAME" -n "$NAMESPACE" -o jsonpath='{.status.phase}' 2>/dev/null || echo "Pending")
        [[ "$PHASE" == "Running" ]] && { RUNNING=true; break; }
        printf "."
        sleep $INTERVAL
        ELAPSED=$((ELAPSED + INTERVAL))
    done
    echo ""

    if ! $RUNNING; then
        _warn "Pod did not reach Running state after ${TIMEOUT}s."
        _warn "Check: kubectl describe pod $POD_NAME -n $NAMESPACE"
        exit 1
    fi
    _ok "Pod is Running."
    echo ""

    # ── Write run script inside the pod ──────────────────────────────────────
    RUN_SCRIPT_NAME="run_${framework}_${model_weights}_server.sh"
    RUN_SCRIPT_PATH="${LOG_DIR}/${RUN_SCRIPT_NAME}"

    _info "Writing server run script inside pod: ${RUN_SCRIPT_PATH}"
    kubectl exec "$POD_NAME" -n "$NAMESPACE" -- bash -c "mkdir -p '${LOG_DIR}'"

    # The run script reads LD_LIBRARY_PATH from PID 1 (set by biren_entrypoint.sh
    # at container start) so kubectl exec sessions get the correct SDK library path.
    _tmp=$(mktemp /tmp/k8s_run_XXXXXX.sh)
    cat > "$_tmp" <<'RUNSCRIPT'
#!/usr/bin/env bash
_ld=$(tr '\0' '\n' < /proc/1/environ | sed -n 's/^LD_LIBRARY_PATH=//p' | head -1)
[[ -n "$_ld" ]] && export LD_LIBRARY_PATH="$_ld"
unset _ld
exec bash "__INNER_SCRIPT__" "__CONFIG_FILE__"
RUNSCRIPT
    sed -i "s|__INNER_SCRIPT__|${INNER_SCRIPT}|g; s|__CONFIG_FILE__|${CONFIG_FILE}|g" "$_tmp"
    kubectl exec -i "$POD_NAME" -n "$NAMESPACE" -- tee "${RUN_SCRIPT_PATH}" < "$_tmp" > /dev/null
    kubectl exec "$POD_NAME" -n "$NAMESPACE" -- chmod +x "${RUN_SCRIPT_PATH}"
    rm -f "$_tmp"

    _ok "Run script  : ${RUN_SCRIPT_PATH}"
    echo ""
    echo "  To start the ${framework} server, run inside the pod:"
    echo "    bash ${RUN_SCRIPT_PATH}"
    echo ""
    echo "── K8s management ──────────────────────────────────────────"
    echo "  kubectl logs $POD_NAME -n ${NAMESPACE} -f"
    echo "  kubectl delete pod $POD_NAME -n ${NAMESPACE}"
    echo ""

    # ── Env-setup snippet for the interactive shell ──────────────────────────
    _env_tmp=$(mktemp /tmp/k8s_env_XXXXXX.sh)
    cat > "$_env_tmp" <<ENVSCRIPT
_ld=\$(tr '\0' '\n' < /proc/1/environ | sed -n 's/^LD_LIBRARY_PATH=//p' | head -1)
[[ -n "\$_ld" ]] && export LD_LIBRARY_PATH="\$_ld"
unset _ld
cd '${LOG_DIR}'
echo ""
echo "  Pod shell — ${framework} interactive session"
echo "  Model    : ${model_weights}"
echo "  Run script ready — start server with:"
echo "    bash ${RUN_SCRIPT_NAME}"
echo ""
ENVSCRIPT
    kubectl exec -i "$POD_NAME" -n "$NAMESPACE" -- tee /tmp/.biren_pod_env.sh < "$_env_tmp" > /dev/null
    rm -f "$_env_tmp"

    _info "Entering interactive shell inside pod at ${LOG_DIR} ..."
    _info "(Type 'exit' or Ctrl-D to leave the pod shell)"
    echo ""

    kubectl exec -it "$POD_NAME" -n "$NAMESPACE" -- \
        bash -c "source /tmp/.biren_pod_env.sh && exec bash -i"

fi
